# camera stuff
RESOLUTION = (640, 480)
FRAMERATE = 60

# homography dimensions
HOMOGRAPHY_RES = 800

# path planning tuning
DESIRED_SPEED = 0
ANGULAR_SPEED_MULTIPLIER = 35
FORWARD_SPEED_MULTIPLIER = 0
MAX_SPEED = 100
MIN_SPEED = 70